name: flutter_app_all
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  mysql_client: ^0.0.27
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.2.1
  stroke_text: ^0.0.3
  google_fonts: ^6.2.1

  screenshot: ^3.0.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  provider: ^6.1.2
  share_plus: ^10.0.2
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo2.png

  fonts:
    - family: Helvetica
      fonts:
      - asset: assets/fonts/Helvetica.ttf
      - asset: assets/fonts/Helvetica-Bold.ttf
        weight: 700
      - asset: assets/fonts/helvetica-light-587ebe5a59211.ttf
        weight: 300
    
