name: flutter_app_all
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  mysql_client: ^0.0.27
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
assets:
  - .env
  
flutter:
  uses-material-design: true
